apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: csi-s3-dir
  volumes:
  - name: csi-s3-dir
    persistentVolumeClaim:
      claimName: csi-s3-pvc
      readOnly: false

