kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: csi-s3-geesefs
provisioner: ru.yandex.s3.csi
parameters:
  mounter: geesefs
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/provisioner-secret-name: csi-s3
  csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
  csi.storage.k8s.io/controller-publish-secret-name: csi-s3
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: csi-s3
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: csi-s3
  bucket: s3-bucket-otus-default
  options: "--uid=1000 --memory-limit 1024 --no-checksum --dir-mode 0777 --file-mode 0666"
