kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  ports:
  - name: http-8081
    protocol: TCP
    port: 8081
    targetPort: 80
  - name: metrics
    port: 9113
    protocol: TCP
    targetPort: 9113
  selector:
    app: nginx
  type: ClusterIP
