apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "otus-externalsecret"
  namespace: vault
spec:
  secretStoreRef:
    name: otus-secretstore
    kind: SecretStore # or ClusterSecretStore
  refreshInterval: "1m"
  target:
    name: otus-cred
  dataFrom:
  - extract:
      key: cred
      version: v1


