apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: otus-secretstore
  namespace: vault
spec:
  retrySettings:
    maxRetries: 5
    retryInterval: "10s"
  provider:
    vault:
      server: "http://vault.vault:8200"
      path: "otus"
      version: "v1"
      namespace: "vault"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "otus"
          serviceAccountRef:
            name: "vault-auth"

