apiVersion: v1
kind: Pod
metadata:
  name: webserver
  namespace: homework
  labels:
    app: webserver
spec:
  volumes:
  - name: web-content
    emptyDir: {}
  initContainers:
  - name: init-container
    image: busybox
    command: ['sh', '-c', 'echo "kubernetes-intro" > index.html && cp index.html init/']
    volumeMounts:
    - name: web-content
      mountPath: /init
  containers:
  - name: web
    image: busybox
    command: ['sh', '-c', 'ls -la /homework && /bin/httpd  -f -p 8000 -h /homework/']
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 200m
        memory: 100Mi
      requests:
        cpu: 200m
        memory: 100Mi
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "ls -l /homework"]
      preStop:
        exec:
          command: ["/bin/sh", "-c", "rm -f /homework/index.html && ls -la /homework"]
    readinessProbe:
      httpGet:
        path: /index.html
        port: 8000
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: web-content
      mountPath: /homework
